"use client";

import { ToastContainer } from "react-toastify";
import "../../public/css/tailwind-ecommerce.css";
import Footer from "./Components/Footer";
import Header from "./Components/Header";
import { Provider } from "react-redux";
import { store } from "./ReduxToolkit/ReduxStore";

// export const metadata = {
//   title: "MayBell - Furniture Store",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <ToastContainer position="bottom-right" autoClose={1000} />
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
