import { ToastContainer } from "react-toastify";
import "../../public/css/tailwind-ecommerce.css";
import Footer from "./Components/Footer";
import Header from "./Components/Header";

export const metadata = {
  title: "MayBell - Furniture Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
